services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    user: root
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    # Optional: install docker-cli automatically on startup
    command: >
      bash -c "apt-get update && apt-get install -y docker-ce-cli && exec /usr/bin/tini -- /usr/local/bin/jenkins.sh"
