version: '3.8'

services:
  jenkins:
    build: .
    container_name: my-jenkins
    user: root
    ports:
      - "9000:8080"      # Jenkins web UI
      - "50000:50000"    # Jenkins agent communication
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
