services:
  jenkins:
    build: .
    container_name: my-jenkins
    user: root
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - C:\Jenkins\jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
