version: '3.8'

services:
  my-jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "9000:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 Jenkins talks to Docker directly
      - /usr/bin/docker:/usr/bin/docker            # 👈 Provides Docker CLI inside Jenkins

volumes:
  jenkins_home:
